env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    github_token: "ENCRYPTED[330bd92269ab42d77f6a60b1df3f7d183a5423e743c85d3fd1a87e390ce761efcd2269fdb22c3f201cabb2fac1a6a370]"
    bot_api: "ENCRYPTED[3851fe106c6e101494ae213a92ea0aac904cf6e7422274b7ecb82df99cd706398f28f141e4591657dd8640cb673a5df2]"
    chat_id: "ENCRYPTED[3c67049344fa82af23fa47a2b562834ae2c706a6ee06f9053d208673bc0b67a91dcb879f02a1d4989ec45f850546341f]"
    git_cookies: 0

# store information about git here
    gmail: reaPeR10x10x@gmail.com

task:
    name: TeamNexus
    timeout_in: 120m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
    download_cc_background_script: # To download cc in background
      - git clone https://$CIRRUS_REPO_OWNER:$github_token@github.com/projects-nexus/ci-script /tmp/cs
      - mv /tmp/cs/* /tmp/ci
      - bash download_cc # cc download script
    sync_script:
      - bash sync
    build_script:
      - bash build
    upload_cc_script: # Upload cc to cloud foreground
      - bash upload_cc # cc uploading script
