env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    my_gh_token: "ENCRYPTED[!31b282eac918e58f307ba3105957ac3bd18cc3ea651015f03232cc1f9b659a846b72975f9dcb639779f78fa21650e52a!]"
    github_token: "ENCRYPTED[!c03c0f090a6ca64cd9ef8c7ff7ef4dd487372a9f43e0f5338d2af08e341b1a6993608f4931e5068eceb0bad0592d717e!]"
    bot_api: "ENCRYPTED[!7ca1019c5fe5c0ec3066352c666675902c1275228b359a597c848196c7c9202608e0e228b8852f1dec8ec3bac703f1e7!]"
    chat_id: "-1001402365506"
    git_cookies: 0
    REAL_REPO_OWNER: "ImSpiDy"

# store information about git here
    gmail: buildbot02@gmail.com

task:
    name: HormYFumcKerz
    timeout_in: 120m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
    down_background_script:
      - git clone https://$CIRRUS_REPO_OWNER:$my_gh_token@github.com/projects-nexus/ci-script /tmp/cs
      - mv /tmp/cs/* /tmp/ci
      - bash down*
    symc_script:
      - bash sy*
    compile_script:
      - bash bu*
    upl_script:
      - bash upl*
